import { seoEvaluationCreateSchema, seoEvaluationResponseSchema, SEO_EVALUATOR_VERSION, SEO_SCHEMA_VERSION, scannerResultSchema, type ControlledQaEvaluationResponse, type QaEvaluation, type SeoEvaluation, type SeoEvaluationCreate, type SeoEvaluationResponse, type ScannerResult } from "@siteprobe/contracts";
import { evaluateScannerResult, runControlledSeoFixture, seoFixtureIdSchema, type ControlledSeoRunResult, type SeoFixtureId } from "@siteprobe/scanner";
import { ControlledEvaluationError } from "./errors.js";
import type { ControlledEvaluationToolConfig } from "./config.js";
import { createApiClient, type ControlledEvaluationApiClient } from "./api-client.js";
import { createSeoApiClient, type SeoEvaluationApiClient } from "./seo-api-client.js";
export type ControlledSeoWorkflowResult = { fixtureId: SeoFixtureId; scannerResult: ScannerResult; evaluation: QaEvaluation; persistedEvaluation: ControlledQaEvaluationResponse; seo: SeoEvaluation; persistedSeoEvaluation: SeoEvaluationResponse };
export type SeoWorkflowDependencies = { runFixture?: (fixtureId: SeoFixtureId) => Promise<ControlledSeoRunResult>; evaluate?: typeof evaluateScannerResult; api?: ControlledEvaluationApiClient; seoApi?: SeoEvaluationApiClient };
export function buildSeoIngestionPayload(scannerResult: ScannerResult, seo: SeoEvaluation, provenance: "controlled-fixture" | "real-site-smoke-test" = "controlled-fixture"): SeoEvaluationCreate { return seoEvaluationCreateSchema.parse({ provenance, schemaVersion: SEO_SCHEMA_VERSION, evaluatorVersion: SEO_EVALUATOR_VERSION, scannerRunId: scannerResult.scanId, requestedUrl: scannerResult.requestedUrl, finalUrl: scannerResult.finalUrl, scannedAt: scannerResult.scannedAt, evaluation: seo }); }
export async function runControlledSeoWorkflow(config: ControlledEvaluationToolConfig, input: unknown, dependencies: SeoWorkflowDependencies = {}): Promise<ControlledSeoWorkflowResult> {
  const parsed = seoFixtureIdSchema.safeParse(input); if (!parsed.success) throw new ControlledEvaluationError("INVALID_FIXTURE", "Unknown controlled SEO fixture"); const fixtureId = parsed.data; const api = dependencies.api ?? createApiClient(config); const seoApi = dependencies.seoApi ?? createSeoApiClient(config); await api.healthCheck(); let run: ControlledSeoRunResult; try { run = await (dependencies.runFixture ?? runControlledSeoFixture)(fixtureId); } catch { throw new ControlledEvaluationError("SCANNER_INVALID_RESULT", "Controlled scanner did not return a valid SEO run"); } const scannerResult = scannerResultSchema.parse(run.scannerResult); let evaluation: QaEvaluation; try { evaluation = (dependencies.evaluate ?? evaluateScannerResult)(scannerResult); } catch { throw new ControlledEvaluationError("EVALUATION_FAILURE", "Controlled QA evaluation failed", { scannerRunId: scannerResult.scanId }); } const core = await api.ingest({ schemaVersion: 1, evaluatorVersion: 1, scannerRunId: scannerResult.scanId, requestedUrl: scannerResult.requestedUrl, finalUrl: scannerResult.finalUrl, scannedAt: scannerResult.scannedAt, evaluation }); let persistedSeoEvaluation: SeoEvaluationResponse; try { persistedSeoEvaluation = seoEvaluationResponseSchema.parse(await seoApi.ingestSeo(buildSeoIngestionPayload(scannerResult, run.seo))); } catch (error) { if (error instanceof ControlledEvaluationError) throw new ControlledEvaluationError(error.stage, error.message, { statusCode: error.statusCode, safeCode: error.safeCode, scannerRunId: scannerResult.scanId }); throw new ControlledEvaluationError("SEO_INGESTION_INVALID_RESPONSE", "API returned an invalid SEO evaluation", { scannerRunId: scannerResult.scanId }); } return { fixtureId, scannerResult, evaluation, persistedEvaluation: core, seo: run.seo, persistedSeoEvaluation };
}
